fixed altdns error on exec
'Queue' module import changed from python2 to python3.
So altdns needs to be installed via python3 command to
avoid error:
ImportError: No module named 'queue'